image: node:10.16.0

pages:
  script:
    - npm install
    - npm install gatsby-cli
    - ./node_modules/.bin/gatsby build --prefix-paths
    - cp ./keybase.txt public/keybase.txt
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master
