image: node:latest

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm install
    - ./node_modules/.bin/gatsby build
    - cp ./keybase.txt public/keybase.txt
  artifacts:
    paths:
      - public
  only:
    - master
