baseurl = "http://wayanjimmy.gitlab.io/"
languageCode = "en-us"
title = "Jimmy Ngoding"
paginate = 5
canonifyurls = true
publishdir = "public"
theme = "cocoa-eh"
disqusshortname = "wayanjimmy-gitlab"
googleanalytics = "UA-81011140-1"
layoutdir = "layouts"
author = "Alexis Tacnet"
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "post/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "catat biar gak lupa"
cover = "https://images.unsplash.com/photo-1465326117523-6450112b60b2?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=f340b4d4a364ac53dcb92955373fc5e0"
author = "Wayan Jimmy"
authorlocation = "Bali"
selfintro= "Will code for food"
github= "wayanjimmy"
twitter= "wayanjimmy"
hideHUGOSupport = false
gatracker= "UA-81011140-1"
logofile = "https://avatars1.githubusercontent.com/u/1282808?v=3&u=881c89cc930dcebaa5d3954889ed30239ea99827&s=400"
email="jimmyeatcrab@gmail.com"
highlightjs=true
latestpostcount = 5
copyright = "Copyright © 2015 Nishanth Shanmugham"
progressively = true
share = false
posts_navigation = true

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
